# Generated by Django 5.0.6 on 2024-06-01 12:18

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_descripcion_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Prueba',
            field=django_quill.fields.QuillField(default=''),
        ),
    ]
