# Generated by Django 5.0.6 on 2024-06-01 12:19

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_prueba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Prueba',
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=django_quill.fields.QuillField(default=''),
        ),
    ]
