# Generated by Django 5.0.6 on 2024-06-01 14:22

import datetime
import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_prueba_alter_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=django_quill.fields.QuillField(blank=True, default='<div></div>', null=True),
        ),
    ]
